# Reference: https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Validation: https://dependabot.com/docs/config-file/validator/

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "black"
      - dependency-name: "ipypton"
      - dependency-name: "isort"
      - dependency-name: "mypy"
      - dependency-name: "pudb"
      - dependency-name: "pytest"