name: "Tests"

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - '**.py'
      - '.github/workflows/tests.yml'
  pull_request:
    branches: main
    paths:
      - '**.py'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run pytest with coverage
      run: pytest --cov