name: Test

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - '**.py'
  pull_request:
    branches: main
    paths:
      - '**.py'
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.12'
    cache: 'pip'
- run: pytest
